#ifndef PANORAMA_IUIPANEL_H
#define PANORAMA_IUIPANEL_H

#ifdef _WIN32
#pragma once
#endif

#include <mathlib/vector.h>
#include <mathlib/vector2d.h>
#include <tier0/platform.h>
#include <tier1/utlvector.h>
#include <panorama/layout/uilength.h>
#include <panorama/panoramasymbol.h>
#include <panorama/panoramatypes.h>

namespace panorama
{

class CJSKeyframesObject;
class CLocVariableValue;
class IUIPanelClient;
class IUIPanelStyle;
class IUIScrollBar;
class IUIWindow;
struct CascadeStyleFileInfo_t;
struct DebugPropertyOutput_t;

enum EAnimationDirection : uint8;
enum EAnimationFillMode : uint8;
enum EPanelRepaint : uint8;
enum EStyleRepaint : uint8;

class ILocVariableSource
{
public:
	virtual ~ILocVariableSource() {}
	virtual const CLocVariableValue *GetLocVariableValue( const CPanoramaSymbol &symName ) const = 0;
};

class IUIPanel : public ILocVariableSource
{
public:
	virtual void Initialize( IUIWindow *window, IUIPanel *parent, const char *pchID, uint32 ePanelFlags ) = 0;
	virtual void InitClonedPanel( IUIPanel *pClone ) = 0;
	virtual void RegisterEventHandlersOnPanel2DType( CPanoramaSymbol symPanelType ) = 0;
	virtual void Shutdown() = 0;
	virtual void FirePanelLoadedEvent() = 0;
	virtual void SetClientPtr( IUIPanelClient *pPtr ) = 0;
	virtual IUIPanelClient *ClientPtr() const = 0;
	virtual void SetID( const char *pchID ) = 0;
	virtual const char *GetID() const = 0;
	virtual CPanoramaSymbol GetPanelType() const = 0;
	virtual bool unk012( CPanoramaSymbol symPanelType ) const = 0;
	virtual bool BHasID() const = 0;
	virtual bool BLoadLayout( const char *pchFile, bool bOverrideExisting = false, bool bPartialLayout = false ) = 0;
	virtual void RequireLoadLayout( const char *pchFile, bool bOverrideExisting = false, bool bPartialLayout = false ) = 0;
	virtual bool BLoadLayoutSnippet( const char *pchSnippetName ) = 0;
	virtual void RequireLoadLayoutSnippet( const char *pchSnippetName ) = 0;
	virtual bool BHasLayoutSnippet( const char *pchSnippetName ) = 0;
	virtual void LoadLayoutAsync( const char *pchFile, bool bOverrideExisting = false, bool bPartialLayout = false ) = 0;
	virtual void *unk020() = 0;
	virtual void *unk021() = 0;
	virtual void UnloadLayout( void ) = 0;
	virtual bool IsLoaded() const = 0;
	virtual void *unk024() = 0;
	virtual void *unk025() = 0;
	virtual void *unk026() = 0;
	virtual void *unk027() = 0;
	virtual void *unk028() = 0;
	virtual void SetParent( IUIPanel *pParent ) = 0;
	virtual void *unk030() = 0;
	virtual IUIPanel *GetParent() const = 0;
	virtual IUIWindow *GetParentWindow() const = 0;
	virtual void SetVisible( bool bVisible ) = 0;
	virtual bool BIsVisible() const = 0;
	virtual bool BIsTransparent() const = 0;
	virtual void SetLayoutLoadedFromParent( IUIPanel *pParent ) = 0;
	virtual void unk037( uint64 unValue ) = 0;
	virtual uint64 *unk038( uint64 *pOut ) const = 0;
	virtual void *unk039() = 0;
	virtual CPanoramaSymbol GetLayoutFile() const = 0;
	virtual CPanoramaSymbol GetLayoutFileLoadedFrom() const = 0;
	virtual int GetLayoutFileReloadCount() const = 0;
	virtual void *unk043() = 0;
	virtual void *unk044() = 0;
	virtual IUIPanel *FindChild( const char *pchID ) = 0;
	virtual IUIPanel *RequireChild( const char *pchID ) = 0;
	virtual IUIPanel *FindChildTraverse( const char *pchID ) = 0;
	virtual IUIPanel *RequireChildTraverse( const char *pchID ) = 0;
	virtual IUIPanel *FindChildInLayoutFile( const char *pchID ) = 0;
	virtual IUIPanel *RequireChildInLayoutFile( const char *pchID ) = 0;
	virtual IUIPanel *FindPanelInLayoutFile( const char *pchID ) = 0;
	virtual IUIPanel *RequirePanelInLayoutFile( const char *pchID ) = 0;
	virtual bool IsDescendantOf( const IUIPanel *pPanel ) const = 0;
	virtual void RemoveAndDeleteChildren() = 0;
	virtual void RemoveAndDeleteChildrenOfType( CPanoramaSymbol symPanelType ) = 0;
	virtual int GetChildCount() const = 0;
	virtual IUIPanel *GetChild( int i ) const = 0;
	virtual IUIPanel *GetFirstChild() const = 0;
	virtual IUIPanel *GetLastChild() const = 0;
	virtual int GetChildIndex( const IUIPanel *pChild ) const = 0;
	virtual uint32 GetChildCountOfType( CPanoramaSymbol symPanelType ) = 0;
	virtual int GetHiddenChildCount() const = 0;
	virtual IUIPanel *GetHiddenChild( int i ) = 0;
	virtual void *unk064() = 0;
	virtual IUIPanel *FindAncestor( const char *pchID ) const = 0;
	virtual IUIPanel *FindLowestCommonAncestor( IUIPanel *pOther ) const = 0;
	virtual void SetRepaint( EPanelRepaint eRepaintNeeded ) = 0;
	virtual void *unk068() = 0;
	virtual void SetAlwaysConsumeHoverClicks( bool bAlwaysConsumeHoverClicks ) = 0;
	virtual void SetCanClearFocusByClicking( bool bCanClearFocusByClicking ) = 0;
	virtual IUIPanelStyle *AccessIUIStyle() = 0;
	virtual IUIPanelStyle *AccessIUIStyleDirty() = 0;
	virtual void ApplyStyles( bool bTraverse ) = 0;
	virtual void AfterStylesApplied( bool bStylesChanged, EStyleRepaint eRepaint, bool bInheritablePropertiesChanged, bool bTraverse ) = 0;
	virtual void SetOnStylesChangedNeeded() = 0;
	virtual void *unk076() = 0;
	virtual const CUtlVector< IUIPanel * > &AccessChildren() = 0;
	virtual void DesiredLayoutSizeTraverse( float *pflDesiredWidth, float *pflDesiredHeight, float flMaxWidth, float flMaxHeight, bool bFinalDimensions ) = 0;
	virtual void DesiredLayoutSizeTraverse( float flMaxWidth, float flMaxHeight ) = 0;
	virtual void OnContentSizeTraverse( float *pflContentWidth, float *pflContentHeight, float flMaxWidth, float flMaxHeight, bool bFinalDimensions ) = 0;
	virtual void LayoutTraverse( float x, float y, float flFinalWidth, float flFinalHeight ) = 0;
	virtual void OnLayoutTraverse( float flFinalWidth, float flFinalHeight ) = 0;
	virtual void SetPositionFromLayoutTraverse( CUILength x, CUILength y, CUILength z ) = 0;
	virtual void InvalidateSizeAndPosition() = 0;
	virtual void InvalidatePosition() = 0;
	virtual void SetActiveSizeAndPositionTransition() = 0;
	virtual void SetActivePositionTransition() = 0;
	virtual bool IsSizeValid() = 0;
	virtual bool IsPositionValid() = 0;
	virtual bool IsChildSizeValid() = 0;
	virtual bool IsChildPositionValid() = 0;
	virtual bool IsSizeTransitioning() = 0;
	virtual bool IsPositionTransitioning() = 0;
	virtual bool IsChildPositionTransitioning() = 0;
	virtual bool IsChildSizeTransitioning() = 0;
	virtual bool TransitionPositionApplied( bool bImmediate ) = 0;
	virtual void *unk097() = 0;
	virtual bool BInvalidateSizeAndPositionOnOpacityChangeDisabled() = 0;
	virtual void *unk099() = 0;
	virtual void *unk100() = 0;
	virtual float GetDesiredLayoutWidth() const = 0;
	virtual float GetDesiredLayoutHeight() const = 0;
	virtual void *unk103() = 0;
	virtual float GetContentWidth() const = 0;
	virtual float GetContentHeight() const = 0;
	virtual void *unk106() = 0;
	virtual float GetActualLayoutWidth() const = 0;
	virtual float GetActualLayoutHeight() const = 0;
	virtual float GetActualRenderWidth() = 0;
	virtual float GetActualRenderHeight() = 0;
	virtual float GetActualXOffset() const = 0;
	virtual float GetActualYOffset() const = 0;
	virtual void *unk113() = 0;
	virtual void *unk114() = 0;
	virtual void *unk115() = 0;
	virtual void *unk116() = 0;
	virtual float GetRawActualXOffset() const = 0;
	virtual float GetRawActualYOffset() const = 0;
	virtual Vector GetActualUIScale() const = 0;
	virtual float GetActualUIScaleX() const = 0;
	virtual float GetActualUIScaleY() const = 0;
	virtual float GetActualUIScaleZ() const = 0;
	virtual Vector GetParentActualUIScale() const = 0;
	virtual EAnimationTimingFunction GetContentsYScrollTransitionTimingFunction() const = 0;
	virtual EAnimationTimingFunction GetContentsXScrollTransitionTimingFunction() const = 0;
	virtual float GetContentsYScrollOffsetTarget() const = 0;
	virtual float GetContentsXScrollOffsetTarget() const = 0;
	virtual double GetContentsXScrollTransitionStart() const = 0;
	virtual double GetContentsYScrollTransitionStart() const = 0;
	virtual double GetContentsXScrollTransitionTime() const = 0;
	virtual double GetContentsYScrollTransitionTime() const = 0;
	virtual void *unk132() = 0;
	virtual void *unk133() = 0;
	virtual void GetContextXScrollTransitionControlPoints( Vector2D ( &vecPoints )[ 4 ] ) const = 0;
	virtual void GetContextYScrollTransitionControlPoints( Vector2D ( &vecPoints )[ 4 ] ) const = 0;
	virtual float GetInterpolatedXScrollOffset() = 0;
	virtual float GetInterpolatedYScrollOffset() = 0;
	virtual bool BScrollInProgress() = 0;
	virtual float StopHorizontalScroll() = 0;
	virtual float StopVerticalScroll() = 0;
	virtual bool BCanDragScroll() = 0;
	virtual bool BCanScrollUp() = 0;
	virtual bool BCanScrollDown() = 0;
	virtual bool BCanScrollLeft() = 0;
	virtual bool BCanScrollRight() = 0;
	virtual void AddClass( CPanoramaSymbol symbol ) = 0;
	virtual void AddClasses( CPanoramaSymbol *pSymbols, uint32 cSymbols ) = 0;
	virtual void AddClassByName( const char *pchName ) = 0;
	virtual void RemoveClass( CPanoramaSymbol symName ) = 0;
	virtual void RemoveClassByName( const char *pchName ) = 0;
	virtual void RemoveClasses( const CPanoramaSymbol *pSymbols, uint32 cSymbols ) = 0;
	virtual void RemoveClassesByName( const char *pchName ) = 0;
	virtual void *unk153() = 0;
	virtual void *unk154() = 0;
	virtual void *unk155() = 0;
	virtual const CUtlVector< CPanoramaSymbol > &GetClasses() const = 0;
	virtual bool BHasClass( CPanoramaSymbol symName ) = 0;
	virtual bool BAscendantHasClass( CPanoramaSymbol symName ) = 0;
	virtual void ToggleClass( CPanoramaSymbol symName ) = 0;
	virtual void SetHasClass( CPanoramaSymbol symName, bool bHasClass ) = 0;
	virtual void SwitchClass( CPanoramaSymbol symAttribute, CPanoramaSymbol symName ) = 0;
	virtual void TriggerClass( CPanoramaSymbol symName ) = 0;
	virtual void *unk163() = 0;
	virtual void *unk164() = 0;
	virtual void *unk165() = 0;
	virtual void *unk166() = 0;
	virtual void *unk167() = 0;
	virtual void SetDefaultFocus( const char *pchChildID ) = 0;
	virtual void *unk169() = 0;
	virtual void *unk170() = 0;
	virtual void *unk171() = 0;
	virtual void *unk172() = 0;
	virtual void *unk173() = 0;
	virtual void *unk174() = 0;
	virtual void *unk175() = 0;
	virtual void *unk176() = 0;
	virtual void *unk177() = 0;
	virtual void *unk178() = 0;
	virtual void *unk179() = 0;
	virtual void *unk180() = 0;
	virtual void *unk181() = 0;
	virtual void *unk182() = 0;
	virtual void *unk183() = 0;
	virtual void *unk184() = 0;
	virtual void *unk185() = 0;
	virtual void *unk186() = 0;
	virtual void *unk187() = 0;
	virtual void *unk188() = 0;
	virtual bool IsInspected() const = 0;
	virtual bool BHasHoverStyle() const = 0;
	virtual void *unk191() = 0;
	virtual bool IsSelected() const = 0;
	virtual bool BHasKeyFocus() const = 0;
	virtual bool BHasDescendantKeyFocus() const = 0;
	virtual void *unk195() = 0;
	virtual void SetDisallowedStyleFlags( uint32 unDisallowedStyleFlags ) = 0;
	virtual uint32 GetDisallowedStyleFlags() const = 0;
	virtual void *unk198() = 0;
	virtual bool IsEnabled() const = 0;
	virtual bool IsActivationEnabled() = 0;
	virtual void *unk201() = 0;
	virtual void *unk202() = 0;
	virtual void *unk203() = 0;
	virtual void *unk204() = 0;
	virtual void *unk205() = 0;
	virtual void *unk206() = 0;
	virtual void *unk207() = 0;
	virtual void *unk208() = 0;
	virtual void *unk209() = 0;
	virtual void *unk210() = 0;
	virtual void *unk211() = 0;
	virtual void *unk212() = 0;
	virtual void *unk213() = 0;
	virtual void *unk214() = 0;
	virtual void *unk215() = 0;
	virtual void *unk216() = 0;
	virtual void *unk217() = 0;
	virtual void *unk218() = 0;
	virtual void *unk219() = 0;
	virtual void *unk220() = 0;
	virtual void *unk221() = 0;
	virtual void *unk222() = 0;
	virtual void *unk223() = 0;
	virtual void *unk224() = 0;
	virtual void *unk225() = 0;
	virtual void *unk226() = 0;
	virtual void *unk227() = 0;
	virtual void *unk228() = 0;
	virtual void *unk229() = 0;
	virtual void *unk230() = 0;
	virtual void *unk231() = 0;
	virtual void *unk232() = 0;
	virtual void *unk233() = 0;
	virtual void *unk234() = 0;
	virtual void *unk235() = 0;
	virtual void *unk236() = 0;
	virtual void *unk237() = 0;
	virtual void *unk238() = 0;
	virtual void *unk239() = 0;
	virtual void *unk240() = 0;
	virtual void *unk241() = 0;
	virtual void *unk242() = 0;
	virtual void *unk243() = 0;
	virtual bool SetFocusToNextPanel( int nRepeats, EFocusMoveDirection moveType, bool bAllowWrap, float flTabIndexCurrent, float flXPosCurrent, float flYPosCurrent, float flXStart, float flYStart ) = 0;
	virtual bool SetInputFocusToFirstOrLastChildInFocusOrder( EFocusMoveDirection moveType, float flXStart, float flYStart ) = 0;
	virtual void *unk246() = 0;
	virtual void *unk247() = 0;
	virtual void *unk248() = 0;
	virtual void *unk249() = 0;
	virtual void *unk250() = 0;
	virtual void *unk251() = 0;
	virtual void *unk252() = 0;
	virtual void *unk253() = 0;
	virtual void *unk254() = 0;
	virtual void *unk255() = 0;
	virtual void *unk256() = 0;
	virtual void *unk257() = 0;
	virtual void *unk258() = 0;
	virtual void *unk259() = 0;
	virtual void *unk260() = 0;
	virtual void *unk261() = 0;
	virtual void *unk262() = 0;
	virtual void *unk263() = 0;
	virtual void *unk264() = 0;
	virtual void *unk265() = 0;
	virtual void *unk266() = 0;
	virtual void AddChild( IUIPanel *pChild ) = 0;
	virtual void RemoveChild( IUIPanel *pChild ) = 0;
	virtual void MoveChildAfter( IUIPanel *pChildToMove, IUIPanel *pBefore ) = 0;
	virtual void MoveChildBefore( IUIPanel *pChildToMove, IUIPanel *pAfter ) = 0;
	virtual void SetMouseCanActivate( EMouseCanActivate eMouseCanActivate, const char *pchOptionalParent = nullptr ) = 0;
	virtual EMouseCanActivate GetMouseCanActivate() = 0;
	virtual IUIPanel *FindParentForMouseCanActivate() = 0;
	virtual bool BReloadLayout( CPanoramaSymbol symPath ) = 0;
	virtual void ReloadStyleFileTraverse( CPanoramaSymbol symPath ) = 0;
	virtual bool BHasOnActivateEvent() = 0;
	virtual bool BHasOnMouseActivateEvent() = 0;
	virtual void SetupJavascriptObjectTemplate() = 0;
	virtual void *unk279() = 0;
	virtual bool BBuildMatchingStyleList( CUtlVector< CascadeStyleFileInfo_t > *pvecStyles ) = 0;
	virtual void *unk281() = 0;
	virtual float GetAttributeFloat( CPanoramaSymbol symName, float flDefaultValue ) const = 0;
	virtual uint64 GetAttributeUInt64( CPanoramaSymbol symName, uint64 unDefaultValue ) const = 0;
	virtual uint32 GetAttributeUInt32( CPanoramaSymbol symName, uint32 unDefaultValue ) const = 0;
	virtual const char *GetAttributeString( CPanoramaSymbol symName, const char *pchDefaultValue ) const = 0;
	virtual int GetAttributeInt( CPanoramaSymbol symName, int nDefaultValue ) const = 0;
	virtual void SetAttributeUInt64( CPanoramaSymbol symName, uint64 unValue ) = 0;
	virtual void SetAttributeFloat( CPanoramaSymbol symName, float flValue ) = 0;
	virtual void unk289( CPanoramaSymbol symName, uint64 unValue ) = 0;
	virtual void SetAttributeUInt32( CPanoramaSymbol symName, uint32 unValue ) = 0;
	virtual void SetAttributeString( CPanoramaSymbol symName, const char *pchValue ) = 0;
	virtual void SetAttributeInt( CPanoramaSymbol symName, int nValue ) = 0;
	virtual bool unk293( CPanoramaSymbol symName ) const = 0;
	virtual void *unk294() = 0;
	virtual void SetAnimation( const char *pchAnimationName, float flDuration, float flDelay, EAnimationTimingFunction eTimingFunc, EAnimationDirection eDirection, EAnimationFillMode eFillMode, float flIterations ) = 0;
	virtual void *unk296() = 0;
	virtual void *unk297() = 0;
	virtual void *unk298() = 0;
	virtual void *unk299() = 0;
	virtual void SetDialogVariable( CPanoramaSymbol symName, const char *pchValue ) = 0;
	virtual void SetDialogVariable_Int( CPanoramaSymbol symName, int nValue ) = 0;
	virtual void SetDialogVariable_UInt64( CPanoramaSymbol symName, uint64 unValue ) = 0;
	virtual void SetDialogVariable_Double( CPanoramaSymbol symName, double flValue ) = 0;
	virtual void SetDialogVariableLocString( CPanoramaSymbol symName, const char *pchValue ) = 0;
	virtual void CloneDialogVariables( IUIPanel *pFrom ) = 0;
	virtual void DirtyDialogVariable( CPanoramaSymbol symName ) = 0;
	virtual void *unk307() = 0;
	virtual void *unk308() = 0;
	virtual void *unk309() = 0;
	virtual void SetPanelIntoContext( IUIPanel *pPanel ) = 0;
	virtual IUIPanel *GetJavaScriptContextParent() const = 0;
	virtual void *unk312() = 0;
	virtual void *unk313() = 0;
	virtual bool BSetProperty( CPanoramaSymbol symName, const char *pchValue ) = 0;
	virtual void GetDebugPropertyInfo( CUtlVector< DebugPropertyOutput_t * > *pvecProperties ) = 0;
	virtual void *unk316() = 0;
	virtual void *unk317() = 0;
	virtual void FindChildrenWithClass( CPanoramaSymbol symClass, CUtlVector< IUIPanel * > &vecMatchingChildren ) = 0;
	virtual void FindChildrenWithClassTraverse( CPanoramaSymbol symClass, CUtlVector< IUIPanel * > &vecMatchingChildren ) = 0;
	virtual void PlayFocusChangeSound( int nRepeats, float flPan ) = 0;
	virtual void *unk321() = 0;
	virtual void *unk322() = 0;
	virtual void ClearPanelEvents( CPanoramaSymbol symPanelEvent ) = 0;
	virtual void *unk324() = 0;
	virtual void *unk325() = 0;
	virtual void *unk326() = 0;
	virtual void SetInScrollbarConstruction( bool bConstructing ) = 0;
	virtual IUIScrollBar *GetVerticalScrollBar() = 0;
	virtual IUIScrollBar *GetHorizontalScrollBar() = 0;
	virtual bool BHasBeenLayedOut() const = 0;
	virtual bool OnStyleTransitionsCleanup() = 0;
	virtual void SetRequireCompositionLayer( bool bRequireCompositionLayer ) = 0;
	virtual bool BRequireCompositionLayer() const = 0;
	virtual void SetAlwaysCacheCompositionLayer( bool bAlwaysCacheCompositionLayer ) = 0;
	virtual bool BAlwaysCacheCompositionLayer() const = 0;
	virtual void SetForceNoCompositionLayer( bool bForceNoCompositionLayer ) = 0;
	virtual bool BForceNoCompositionLayer() const = 0;
	virtual void *unk338() = 0;
	virtual void *unk339() = 0;
	virtual void SetReadyForDisplay( bool bReady ) = 0;
	virtual void RegisterForReadyEvents( bool bEnable ) = 0;
	virtual void *unk342() = 0;
	virtual float StopAnimationOfPropertyUntilFrameUpdateAndGetStopTime( uint32 hSymbol ) = 0;
	virtual bool BHasCachedCommandList() const = 0;
	virtual uint32 GetCommandListBytesSize() const = 0;
	virtual float GetRepaintRate() const = 0;
	virtual bool BUsesGlobalContext() const = 0;
	virtual void SetUseGlobalContext( bool bUseGlobalContext ) = 0;
	virtual CJSKeyframesObject *JSCreateCopyOfCSSKeyframes( const char *pchKeyframesName ) = 0;
	virtual void *unk350() = 0;
	virtual void *unk351() = 0;
	virtual void *unk352() = 0;
	virtual void *unk353() = 0;
};

} // namespace panorama

#endif
