if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

# Renders each element of LIST (a plain value or a generator expression) as a
# YAML sequence item "    - '<PREFIX><element>'" ending with a newline. An empty
# list renders nothing. Evaluated at generate time, so it is safe for
# $<TARGET_PROPERTY:...> input.
function(sourcesdk_clangd_yaml_items OUT_VAR PREFIX LIST)
	set(ITEM_BEGIN "    - '${PREFIX}")
	set(ITEM_END "'\n")

	set(${OUT_VAR} "$<$<BOOL:${LIST}>:${ITEM_BEGIN}$<JOIN:${LIST},${ITEM_END}${ITEM_BEGIN}>${ITEM_END}>" PARENT_SCOPE)
endfunction()

# Writes a .clangd fragment that feeds clangd the include directories, compile
# definitions and compile options of a target for files that are absent from
# compile_commands.json (headers of header-only or single-TU projects). Without
# it clangd borrows the flags of the nearest listed file, which is usually a
# thirdparty source with an unrelated flag set.
#
# sourcesdk_generate_clangd(
# 	TARGET <target>
# 	[OUTPUT <file>]             # default: <current source dir>/.clangd
# 	[PATH_MATCH <regex>...]     # default: .* (relative to the .clangd directory)
# )
function(sourcesdk_generate_clangd)
	cmake_parse_arguments(CLANGD "" "TARGET;OUTPUT" "PATH_MATCH" ${ARGN})

	if(NOT CLANGD_TARGET)
		message(FATAL_ERROR "sourcesdk_generate_clangd: TARGET is required")
	endif()

	if(NOT TARGET ${CLANGD_TARGET})
		message(FATAL_ERROR "sourcesdk_generate_clangd: \"${CLANGD_TARGET}\" is not a target")
	endif()

	if(NOT CLANGD_OUTPUT)
		set(CLANGD_OUTPUT "${CMAKE_CURRENT_SOURCE_DIR}/.clangd")
	endif()

	if(NOT CLANGD_PATH_MATCH)
		set(CLANGD_PATH_MATCH ".*")
	endif()

	list(JOIN CLANGD_PATH_MATCH ", " CLANGD_PATH_MATCH_LIST)

	# Standard flag as CMake would pass it (-std=c++17 / -std:c++latest / -std=gnu++17).
	get_target_property(CLANGD_CXX_STANDARD ${CLANGD_TARGET} CXX_STANDARD)
	get_target_property(CLANGD_CXX_EXTENSIONS ${CLANGD_TARGET} CXX_EXTENSIONS)

	if(NOT CLANGD_CXX_STANDARD)
		set(CLANGD_CXX_STANDARD "${CMAKE_CXX_STANDARD}")
	endif()

	if(CLANGD_CXX_EXTENSIONS STREQUAL "CLANGD_CXX_EXTENSIONS-NOTFOUND")
		set(CLANGD_CXX_EXTENSIONS "${CMAKE_CXX_EXTENSIONS}")
	endif()

	if(CLANGD_CXX_EXTENSIONS)
		set(CLANGD_STD_OPTION "${CMAKE_CXX${CLANGD_CXX_STANDARD}_EXTENSION_COMPILE_OPTION}")
	else()
		set(CLANGD_STD_OPTION "${CMAKE_CXX${CLANGD_CXX_STANDARD}_STANDARD_COMPILE_OPTION}")
	endif()

	# TARGET_PROPERTY also pulls transitive usage requirements, which repeat a lot.
	set(CLANGD_INCLUDES "$<REMOVE_DUPLICATES:$<TARGET_PROPERTY:${CLANGD_TARGET},INCLUDE_DIRECTORIES>>")
	set(CLANGD_DEFINITIONS "$<REMOVE_DUPLICATES:$<TARGET_PROPERTY:${CLANGD_TARGET},COMPILE_DEFINITIONS>>")
	set(CLANGD_OPTIONS "$<REMOVE_DUPLICATES:$<TARGET_PROPERTY:${CLANGD_TARGET},COMPILE_OPTIONS>>")

	sourcesdk_clangd_yaml_items(CLANGD_STD_ITEMS "" "${CLANGD_STD_OPTION}")
	sourcesdk_clangd_yaml_items(CLANGD_INCLUDE_ITEMS "-I" "${CLANGD_INCLUDES}")
	sourcesdk_clangd_yaml_items(CLANGD_DEFINITION_ITEMS "-D" "${CLANGD_DEFINITIONS}")
	sourcesdk_clangd_yaml_items(CLANGD_OPTION_ITEMS "" "${CLANGD_OPTIONS}")

	string(JOIN "\n" CLANGD_CONTENT
		"# Generated by sourcesdk_generate_clangd() for target \"${CLANGD_TARGET}\". Reconfigure instead of editing."
		"If:"
		"  PathMatch: [${CLANGD_PATH_MATCH_LIST}]"
		"CompileFlags:"
		"  Remove: [-I*, /I*, -std*, /std*]"
		"  Add:"
		"${CLANGD_STD_ITEMS}${CLANGD_INCLUDE_ITEMS}${CLANGD_DEFINITION_ITEMS}${CLANGD_OPTION_ITEMS}"
	)

	get_property(CLANGD_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

	# file(GENERATE) runs once per configuration; a single output needs a single one.
	if(CLANGD_MULTI_CONFIG)
		list(GET CMAKE_CONFIGURATION_TYPES 0 CLANGD_CONFIG)
		file(GENERATE OUTPUT "${CLANGD_OUTPUT}" CONTENT "${CLANGD_CONTENT}" CONDITION "$<CONFIG:${CLANGD_CONFIG}>")
	else()
		file(GENERATE OUTPUT "${CLANGD_OUTPUT}" CONTENT "${CLANGD_CONTENT}")
	endif()
endfunction()

if(SOURCESDK_GENERATE_CLANGD)
	sourcesdk_generate_clangd(
		TARGET ${PROJECT_NAME}
		OUTPUT "${SOURCESDK_DIR}/.clangd"
		PATH_MATCH
			common/.*
			entity2/.*
			game/.*
			interfaces/.*
			mathlib/.*
			networksystem/.*
			public/.*
			tier1/.*
	)
endif()
