if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_INTERFACES_DIR)
	message(FATAL_ERROR "SOURCESDK_INTERFACES_DIR is empty")
endif()

set(SOURCESDK_INTERFACES_NAME "interfaces")
set(SOURCESDK_INTERFACES_OUTPUT_NAME "${SOURCESDK_INTERFACES_NAME}")

set(SOURCESDK_INTERFACES_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_INTERFACES_LINK_OPTIONS
	${SOURCESDK_LINK_OPTIONS}
)

set(SOURCESDK_INTERFACES_COMPILE_DEFINITIONS
	${SOURCESDK_COMPILE_DEFINITIONS}

	_LIB
)

if(SOURCESDK_CREATE_INTEFACE_OVERRIDE)
	list(APPEND SOURCESDK_INTERFACES_COMPILE_DEFINITIONS CREATE_INTEFACE_OVERRIDE)
endif()

set(SOURCESDK_PUBLIC_INTERFACES_INCLUDE_DIR "${SOURCESDK_DIR}/interfaces")

set(SOURCESDK_INTERFACES_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_INTERFACES_INCLUDE_DIR}
	${SOURCESDK_PUBLIC_DIR}/tier0
	${SOURCESDK_PUBLIC_DIR}/tier1
	${SOURCESDK_PUBLIC_DIR}
)

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_INTERFACES_INCLUDE_DIR}
)

set(SOURCESDK_INTERFACES_SOURCE_FILES
	${SOURCESDK_INTERFACES_DIR}/interfaces.cpp
)

add_library(${SOURCESDK_INTERFACES_NAME} STATIC ${SOURCESDK_INTERFACES_SOURCE_FILES})
add_library(${PROJECT_NAME}::${SOURCESDK_INTERFACES_NAME} ALIAS ${SOURCESDK_INTERFACES_NAME})

set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES
	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF

	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_INTERFACES_OUTPUT_NAME})

if(WINDOWS)
	if(SOURCESDK_MSVC_RUNTIME_LIBRARY)
		set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
	endif()
elseif(MACOS)
	set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES OSX_ARCHITECTURES "x86_64")
endif()

target_compile_options(${SOURCESDK_INTERFACES_NAME} PUBLIC ${PLATFORM_COMPILE_OPTIONS} ${SOURCESDK_INTERFACES_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_INTERFACES_NAME} PUBLIC ${PLATFORM_LINK_OPTIONS} ${SOURCESDK_INTERFACES_LINK_OPTIONS})

target_compile_definitions(${SOURCESDK_INTERFACES_NAME} PUBLIC ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_INTERFACES_COMPILE_DEFINITIONS})
target_include_directories(${SOURCESDK_INTERFACES_NAME} PUBLIC ${PLATFORM_INCLUDE_DIRS} ${SOURCESDK_INTERFACES_INCLUDE_DIRS})
