if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_MATHLIB_DIR)
	message(FATAL_ERROR "SOURCESDK_MATHLIB_DIR is empty")
endif()

set(SOURCESDK_MATHLIB_NAME "mathlib")
set(SOURCESDK_MATHLIB_OUTPUT_NAME "math")

set(SOURCESDK_MATHLIB_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_MATHLIB_LINK_OPTIONS
	${SOURCESDK_LINK_OPTIONS}
)

set(SOURCESDK_MATHLIB_COMPILE_DEFINITIONS
	${SOURCESDK_COMPILE_DEFINITIONS}

	_LIB
)

set(SOURCESDK_PUBLIC_MATHLIB_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/mathlib")

set(SOURCESDK_MATHLIB_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_MATHLIB_INCLUDE_DIR}
	${SOURCESDK_PUBLIC_DIR}/tier0
	${SOURCESDK_PUBLIC_DIR}/tier1
	${SOURCESDK_PUBLIC_DIR}
)

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_MATHLIB_INCLUDE_DIR}
)

set(SOURCESDK_MATHLIB_SOURCE_FILES
	${SOURCESDK_MATHLIB_DIR}/anorms.cpp
	${SOURCESDK_MATHLIB_DIR}/bumpvects.cpp
	${SOURCESDK_MATHLIB_DIR}/color_conversion.cpp
	${SOURCESDK_MATHLIB_DIR}/halton.cpp
	${SOURCESDK_MATHLIB_DIR}/IceKey.cpp
	${SOURCESDK_MATHLIB_DIR}/imagequant.cpp
	${SOURCESDK_MATHLIB_DIR}/lightdesc.cpp
	${SOURCESDK_MATHLIB_DIR}/mathlib_base.cpp
	${SOURCESDK_MATHLIB_DIR}/polyhedron.cpp
	${SOURCESDK_MATHLIB_DIR}/powsse.cpp
	${SOURCESDK_MATHLIB_DIR}/quantize.cpp
	${SOURCESDK_MATHLIB_DIR}/randsse.cpp
	${SOURCESDK_MATHLIB_DIR}/simdvectormatrix.cpp
	${SOURCESDK_MATHLIB_DIR}/sparse_convolution_noise.cpp
	${SOURCESDK_MATHLIB_DIR}/sse.cpp
	${SOURCESDK_MATHLIB_DIR}/sseconst.cpp
	${SOURCESDK_MATHLIB_DIR}/ssenoise.cpp
	${SOURCESDK_MATHLIB_DIR}/vmatrix.cpp
)

add_library(${SOURCESDK_MATHLIB_NAME} STATIC ${SOURCESDK_MATHLIB_SOURCE_FILES})
add_library(${PROJECT_NAME}::${SOURCESDK_MATHLIB_NAME} ALIAS ${SOURCESDK_MATHLIB_NAME})

set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES
	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF

	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_MATHLIB_OUTPUT_NAME})

if(WINDOWS)
	if(SOURCESDK_MSVC_RUNTIME_LIBRARY)
		set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
	endif()
elseif(MACOS)
	set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES OSX_ARCHITECTURES "x86_64")
endif()

target_compile_options(${SOURCESDK_MATHLIB_NAME} PUBLIC ${PLATFORM_COMPILE_OPTIONS} ${SOURCESDK_MATHLIB_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_MATHLIB_NAME} PUBLIC ${PLATFORM_LINK_OPTIONS} ${SOURCESDK_MATHLIB_LINK_OPTIONS})

target_compile_definitions(${SOURCESDK_MATHLIB_NAME} PUBLIC ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_MATHLIB_COMPILE_DEFINITIONS})
target_include_directories(${SOURCESDK_MATHLIB_NAME} PUBLIC ${PLATFORM_INCLUDE_DIRS} ${SOURCESDK_MATHLIB_INCLUDE_DIRS})
