if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_NETWORKSYSTEM_DIR)
	message(FATAL_ERROR "SOURCESDK_NETWORKSYSTEM_DIR is empty")
endif()

set(SOURCESDK_NETWORKSYSTEM_NAME "networksystem")
set(SOURCESDK_NETWORKSYSTEM_OUTPUT_NAME "${SOURCESDK_NETWORKSYSTEM_NAME}")

set(SOURCESDK_NETWORKSYSTEM_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_NETWORKSYSTEM_LINK_OPTIONS
	${SOURCESDK_LINK_OPTIONS}
)

set(SOURCESDK_NETWORKSYSTEM_COMPILE_DEFINITIONS
	${SOURCESDK_COMPILE_DEFINITIONS}

	_LIB
)

set(SOURCESDK_PUBLIC_NETWORKSYSTEM_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/networksystem")

set(SOURCESDK_NETWORKSYSTEM_INCLUDE_DIRS
	${SOURCESDK_COMMON_DIR}
	${SOURCESDK_PROTOBUF_SOURCE_DIR}
	${SOURCESDK_DIR}/game/shared
	${SOURCESDK_PUBLIC_DIR}/engine
	${SOURCESDK_PUBLIC_NETWORKSYSTEM_INCLUDE_DIR}
	${SOURCESDK_PUBLIC_DIR}/mathlib
	${SOURCESDK_PUBLIC_DIR}/tier0
	${SOURCESDK_PUBLIC_DIR}/tier1
	${SOURCESDK_PUBLIC_DIR}
	${SOURCESDK_PROTO_OUTPUT_DIR}
)

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_NETWORKSYSTEM_INCLUDE_DIR}
)

set(SOURCESDK_NETWORKSYSTEM_SOURCE_FILES
	${SOURCESDK_NETWORKSYSTEM_DIR}/networkmessages.cpp
)

add_library(${SOURCESDK_NETWORKSYSTEM_NAME} STATIC ${SOURCESDK_NETWORKSYSTEM_SOURCE_FILES})
add_library(${PROJECT_NAME}::${SOURCESDK_NETWORKSYSTEM_NAME} ALIAS ${SOURCESDK_NETWORKSYSTEM_NAME})

set_target_properties(${SOURCESDK_NETWORKSYSTEM_NAME} PROPERTIES
	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF

	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_NETWORKSYSTEM_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_NETWORKSYSTEM_OUTPUT_NAME})

if(WINDOWS)
	if(SOURCESDK_MSVC_RUNTIME_LIBRARY)
		set_target_properties(${SOURCESDK_NETWORKSYSTEM_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
	endif()
elseif(MACOS)
	set_target_properties(${SOURCESDK_NETWORKSYSTEM_NAME} PROPERTIES OSX_ARCHITECTURES "x86_64")
endif()

target_compile_options(${SOURCESDK_NETWORKSYSTEM_NAME} PUBLIC ${PLATFORM_COMPILE_OPTIONS} ${SOURCESDK_NETWORKSYSTEM_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_NETWORKSYSTEM_NAME} PUBLIC ${PLATFORM_LINK_OPTIONS} ${SOURCESDK_NETWORKSYSTEM_LINK_OPTIONS})

target_compile_definitions(${SOURCESDK_NETWORKSYSTEM_NAME} PUBLIC ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_NETWORKSYSTEM_COMPILE_DEFINITIONS})
target_include_directories(${SOURCESDK_NETWORKSYSTEM_NAME} PUBLIC ${PLATFORM_INCLUDE_DIRS} ${SOURCESDK_NETWORKSYSTEM_INCLUDE_DIRS})
