if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8) # 64-bit
	set(SOURCESDK_COMPILE_DEFINITIONS
		${SOURCESDK_COMPILE_DEFINITIONS}

		PLATFORM_64BITS X64BITS
	)
else()
	set(SIZEOF_BITS ${CMAKE_SIZEOF_VOID_P})
	math(EXPR SIZEOF_BITS "${SIZEOF_BITS}*8")
	message(FATAL_ERROR "${SIZEOF_BITS}-bit platform is not supported")
endif()

set(SOURCESDK_PROTO_DIRS
	${SOURCESDK_PROTO_DIRS}
)

if(WINDOWS)
	set(SOURCESDK_COMPILE_DEFINITIONS
		${SOURCESDK_COMPILE_DEFINITIONS}

		_WIN32 WIN32
	)
elseif(LINUX)
	set(SOURCESDK_COMPILE_DEFINITIONS
		${SOURCESDK_COMPILE_DEFINITIONS}

		POSIX
		_LINUX LINUX
	)
elseif(APPLE)
	set(SOURCESDK_COMPILE_DEFINITIONS
		${SOURCESDK_COMPILE_DEFINITIONS}

		POSIX
		OSX _OSX
	)
endif()

if(MSVC)
	set(SOURCESDK_COMPILE_DEFINITIONS
		${SOURCESDK_COMPILE_DEFINITIONS}

		COMPILER_MSVC COMPILER_MSVC64
	)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set(PLATFORM_COMPILE_DEFINITIONS
		${PLATFORM_COMPILE_DEFINITIONS}

		_DEBUG DEBUG
	)
endif()

set(SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_INCLUDE_DIRS}
)

if(SOURCESDK_MALLOC_OVERRIDE)
	set(SOURCESDK_SOURCE_FILES
		${SOURCESDK_SOURCE_FILES}

		${SOURCESDK_PUBLIC_DIR}/tier0/memoverride_new.cpp
	)
else()
	set(SOURCESDK_SOURCE_FILES
		${SOURCESDK_SOURCE_FILES}

		# dummy cpp file
		${SOURCESDK_COMMON_DIR}/main.cpp
	)
endif()

set(SOURCESDK_LIB_DIR "${SOURCESDK_DIR}/lib")

set(SOURCESDK_LINK_LIBRARIES
	${SOURCESDK_LINK_LIBRARIES}
)

if(WINDOWS)
	set(SOURCESDK_PLATFORM_DIR "win64")
elseif(LINUX)
	set(SOURCESDK_PLATFORM_DIR "linuxsteamrt64")
elseif(APPLE)
	set(SOURCESDK_PLATFORM_DIR "osx64")
else()
	message(FATAL_ERROR "Unsupported platform")
endif()

set(SOURCESDK_LIB_PLATFORM_DIR "${SOURCESDK_LIB_DIR}/${SOURCESDK_PLATFORM_DIR}")

set(SOURCESDK_PATCHELF_EXE "patchelf${CMAKE_EXECUTABLE_SUFFIX}")
set(SOURCESDK_PATCHELF_EXECUTABLE "${DEVTOOLS_BIN_DIR}/${SOURCESDK_PLATFORM_DIR}/${SOURCESDK_PATCHELF_EXE}")

function(append_sourcesdk_shared_library LIB_NAME LIB_FILENAME_OUT IMPLIB_FILENAME_OUT)
	set(SOURCESDK_SHARED_LIBRARY_LIB_NAME "${CMAKE_SHARED_LIBRARY_PREFIX}${LIB_NAME}")
	set(SOURCESDK_APPEND_SHARED_LIBRARY_LIB "${SOURCESDK_LIB_PLATFORM_DIR}/${SOURCESDK_SHARED_LIBRARY_LIB}")

	set(LIB_FILENAME "${SOURCESDK_APPEND_SHARED_LIBRARY_LIB}${SOURCESDK_SHARED_LIBRARY_LIB_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}")
	set(IMPLIB_FILENAME "${SOURCESDK_APPEND_SHARED_LIBRARY_LIB}${SOURCESDK_SHARED_LIBRARY_LIB_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX}")
	set(${LIB_FILENAME_OUT} ${LIB_FILENAME} PARENT_SCOPE)
	set(${IMPLIB_FILENAME_OUT} ${IMPLIB_FILENAME} PARENT_SCOPE)

	if(SOURCESDK_LINK_STRIP_CPP_EXPORTS AND LINUX)
		set(SOURCESDK_SHARED_LIBRARY_LIB "${SOURCESDK_SHARED_LIBRARY_LIB_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}")
		set(SOURCESDK_BINARY_SHARED_LIBRARY_LIB "${CMAKE_BINARY_DIR}/${SOURCESDK_SHARED_LIBRARY_LIB}")

		if(NOT EXISTS ${SOURCESDK_BINARY_SHARED_LIBRARY_LIB})
			configure_file(${LIB_FILENAME} ${SOURCESDK_BINARY_SHARED_LIBRARY_LIB} COPYONLY)

			message(STATUS "Patching ${SOURCESDK_SHARED_LIBRARY_LIB} ...")
			execute_process(
				COMMAND bash -c "readelf -Ws --dyn-syms ${SOURCESDK_SHARED_LIBRARY_LIB} | awk '{print $8}' | grep -E '_ZS|_ZNS|_ZNKS|_ZN9__gnu_cxx|_ZNK9__gnu_cxx|_ZTIS|_ZTT|_ZTSS|_Zd|_Zn|_NSd|St[0-9]|Si[0-9]|__cxxabiv1' | awk '{print substr($0, 3)}' | awk '{print \"_Z\" $0 \" XX\" $0}' | sort -u >> ${SOURCESDK_SHARED_LIBRARY_LIB_NAME}.map && { readelf -Ws --dyn-syms ${SOURCESDK_SHARED_LIBRARY_LIB} | awk '$7 != \"UND\" {print $8}' | sed 's/@.*//' | grep -E '^(__gxx_personality|__cxa_|__dynamic_cast)' | grep -v -E '^__cxa_(atexit|finalize|thread_atexit)$' | sort -u | awk '{print $0 \" XX\" $0}' >> ${SOURCESDK_SHARED_LIBRARY_LIB_NAME}.map || true; } && \"${SOURCESDK_PATCHELF_EXECUTABLE}\" --output ${SOURCESDK_SHARED_LIBRARY_LIB} --rename-dynamic-symbols ${SOURCESDK_SHARED_LIBRARY_LIB_NAME}.map ${SOURCESDK_SHARED_LIBRARY_LIB}"
				WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
				RESULT_VARIABLE SOURCESDK_PATCHELF_RESULT
				ERROR_VARIABLE SOURCESDK_PATCHELF_ERROR
			)

			if(NOT SOURCESDK_PATCHELF_RESULT EQUAL 0)
				message(FATAL_ERROR "Failed to execute (${SOURCESDK_PATCHELF_RESULT}):\n${SOURCESDK_PATCHELF_ERROR}")
			endif()
		endif()

		set(${LIB_FILENAME_OUT} "${SOURCESDK_BINARY_SHARED_LIBRARY_LIB}" PARENT_SCOPE)
	endif()
endfunction()
